#!/usr/bin/Rscript

# Load Achilles and httr.
library(Achilles)
library(httr)

# Get passed environment variables.
env_var_names <- list("ACHILLES_SOURCE", "ACHILLES_DB_URI",
                      "ACHILLES_CDM_SCHEMA", "ACHILLES_VOCAB_SCHEMA",
                      "ACHILLES_RES_SCHEMA", "ACHILLES_OUTPUT_BASE",
                      "ACHILLES_CDM_VERSION")
env_vars <- Sys.getenv(env_var_names, unset=NA)

# Replace unset environement variables with defaults.
default_vars <- list("DEFAULT", "postgresql://lifebell-mimiciv.c8hzbtpbj5kk.us-east-2.rds.amazonaws.com:5432/mimiciv?user=postgres&password=KglQkgAEmfISxXRY5CYL",
                     "omop", "omop", "omop", "./output", "5.3")
env_vars[is.na(env_vars)] <- default_vars[is.na(env_vars)]

# Create name to tag results and output path from ACHILLES_SOURCE and timestamp
current_datetime <- strftime(Sys.time(), format="%Y-%m-%dT%H.%M.%S")
output_path <- paste(env_vars$ACHILLES_OUTPUT_BASE, env_vars$ACHILLES_SOURCE,
                     current_datetime, sep="/")
dir.create(output_path, showWarnings=FALSE, recursive=TRUE, mode="0755")

# Parse DB URI into pieces.
db_conf <- parse_url(env_vars$ACHILLES_DB_URI)

# Some connection packages need the database on the server argument.
server <- paste(db_conf$hostname, db_conf$path, sep="/")

#Set JdbcDriver folder and download driver 
Sys.setenv("DATABASECONNECTOR_JAR_FOLDER" = "c:/temp/jdbcDrivers")
downloadJdbcDrivers("postgresql")

# Create connection details using DatabaseConnector utility.
connectionDetails <- createConnectionDetails(
    dbms="postgresql",
    user="postgres",
    password="KglQkgAEmfISxXRY5CYL",
    server="lifebell-mimiciv.c8hzbtpbj5kk.us-east-2.rds.amazonaws.com/mimiciv", 
    port="5432"
)

cat("DATABASE CONNECTEDDDDDDDD!!!!!! WOOT WOOT!!!!!!!!!!")
print(connectionDetails)

args <- commandArgs(trailingOnly = TRUE)

createIndices <- (db_conf$scheme != "redshift" && db_conf$scheme != "netezza")

if (length(args) == 0 || args[1] != "heel") {

    # Run Achilles report and generate data in the results schema.
    achillesResults <- achilles(
        connectionDetails, cdmDatabaseSchema="omop",
        resultsDatabaseSchema="achilles_results",
        vocabDatabaseSchema="omop",
        scratchDatabaseSchema = "achilles_results",
        sourceName="mimiciv",
        cdmVersion="5.3",
        createIndices=createIndices,
        createTable=TRUE
    )
    
} else {

    # Run Achilles Heel only
    achillesHeel(
	      connectionDetails,
	      cdmDatabaseSchema=env_vars$ACHILLES_CDM_SCHEMA,
        resultsDatabaseSchema=env_vars$ACHILLES_RES_SCHEMA,
        vocabDatabaseSchema=env_vars$ACHILLES_VOCAB_SCHEMA,
        cdmVersion=env_vars$ACHILLES_CDM_VERSION)

}

# Export Achilles results to output path in JSON format.
exportToJson(connectionDetails,"omop", "achilles_results", "C:\Users\achav\Repos\AchillesWeb\AchillesWeb\data")
